export const QUERY_KEYS = {
  AUTH_LOGIN: "authLogin",
  PRODUCTS_SEARCH: "products",
  CATEGORIES: "categories",
  SUBCATEGORIES_BY_CATEGORY_ID: "subcategories",
  ADD_PRODUCT: "addProduct",
  PRODUCT: "product",
  USER: "user",
  DELETE_PRODUCT: "deleteProduct",
  ADD_TO_CART: "addToCart",
  CART: "cart",
  CART_SUMMARY: "summary",
  UPDATE_CART_ITEM: "updateCartItem",
  DELETE_CART_ITEM: "deleteCartItem",
};
